# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core 3.0'
  inputs:
    version: 3.0.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: 'Dotnet.Container.Sln'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: restore
    arguments: /p:PackageOutputPath=$(Build.ArtifactStagingDirectory) /p:VersionSuffix=build$(Build.BuildNumber)
    projects: $(Build.Repository.LocalPath)/src/dotnet-container/dotnet-container.csproj

- task: PublishPipelineArtifact@0
  displayName: 'Publish package'
  inputs:
    artifactName: 'package'
    targetPath: '$(Build.ArtifactStagingDirectory)'
