# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel release/3.0.1xx
  displayName: 'Install .NET Core'

- script: echo '##vso[task.prependpath]/home/vsts/.dotnet'
  displayName: 'Add .NET to PATH'

- script: dotnet restore'
  displayName: 'dotnet restore'

